### ISSUE TITLE
Peer-review week 3 module II

### ISSUE THREAD

**Issue by daudi13** [Bavon101/todoList#10]
No major issues were found in your code,

- you documented your code according to github workflow requirements
- your code worked as per the requirement from the assignment
- you had no linter errors.
- All your testing passed.
keep up the good work

**Comment by Bavon101** [comment]
@daudi13 Thanks for the feedback.
<img src="https://media4.giphy.com/media/26tn33aiTi1jkl6H6/giphy.gif"/>
Cheers and happy coding.🐱‍👤🐱‍🏍
