### ISSUE TITLE
Peer review: Module 2 - Week 2 - Day 4

### ISSUE THREAD

**Issue by jssol** [Bavon101/todoList#3]
- It will improve the app if the user is not able to have duplicate tasks in the list.
- The app still adds an empty task to the list, please make sure to prevent that.
- The app should trim the task string before adding it.

**Comment by Bavon101** [comment]
@jssol  Thanks for catching these issues ill tackle them 🐱‍🏍.

**Comment by Bavon101** [comment]
@jssol I'm glad to have been able to fix the issues you highlighted thanks once more 🐱‍💻.
